<!-- BEGIN POST -->
        <div class="box">
          <div class="container">
            <div class="title">
              <div class="meta">
                <p class="comments-count"><a href="post_page.html#comments" title="5 comments"><span>5</span> comments</a></p>
                <p class="author"><a href="#null" title="Kuba Sto">Kuba Sto</a></p>
                <p>Category one, Category two</p>
                <p>September 21, 2010</p>
              </div>
              <div class="top"></div>
              <h2><a href="http://themeforest.net/item/stuff-template/127580/?ref=kubasto" title="Buy this template for $16 on ThemeForest.net">Buy this template for $16 on ThemeForest.net</a></h2>
            </div>
            <div class="thumbnail">
              <a href="post_page.html" title="Buy this template for $16 on ThemeForest.net">
                <img src="content/small/p1/a.jpg" alt="" />
                <span class="badge hot"></span>
              </a>
            </div>
            <div class="excerpt">
              <p>This is&nbsp;a&nbsp;premium website template and <a href="http://themeforest.net/item/stuff-template/127580/?ref=kubasto">you can buy it&nbsp;on&nbsp;this page</a>.</p>
              <p>You can also read more about all the features an contact me for questions and support. Also, I provide free support for all buyers. All images used for the demo site comes from <a style="white-space: nowrap;" href="http://www.flickr.com/photos/x-ray_delta_one/">x-ray delta one</a>, and are not included to the theme. Thank you.</p>
            </div>
            <div class="bottom"></div>
            <a href="http://themeforest.net/item/stuff-template/127580/?ref=kubasto" title="Read more" class="more">Read more</a>
          </div>
        </div>
        <!-- END POST -->
        
        <!-- BEGIN POST -->
        <div class="box">
          <div class="container">
            <div class="title">
              <div class="meta">
                <p class="comments-count"><a href="post_page.html#comments" title="12 comments"><span>12</span> comments</a></p>
                <p class="author"><a href="#null" title="Second author">Second author</a></p>
                <p>Category one</p>
                <p>September 20, 2010</p>
              </div>
              <div class="top"></div>
              <h2><a href="post_page.html" title="Next new item">Next new item</a></h2>
            </div>
            <div class="thumbnail">
              <a href="post_page.html" title="Next new item">
                <img src="content/small/p2/a.jpg" alt="" />
                <span class="badge new"></span>
              </a>
            </div>
            <div class="excerpt">
              <p>Per adhuc mandamus et, eius utamur te&nbsp;mel. Vel duis voluptaria ne. Eumid iudicabit efficiendi, quodsi vivendo conceptam eu&nbsp;sed. Ut&nbsp;mel eratorus suscipiantur consectetuer, ex&nbsp;quo novum saperet fierent. Nobis delenit novim conceptam.</p>
              <p>Tantas utinam ad&nbsp;pro, vix quidam docendi ut. Timeam placerat deus reprehendunt vim ne. Per adhuc mandamus et, eius utamur te&nbsp;mel. Velduis voluptaria ne. Conceptamus ides iudicabit.</p>
            </div>
            <div class="bottom"></div>
            <a href="post_page.html" title="Read more" class="more">Read more</a>
          </div>
        </div>
        <!-- END POST -->
        
        <!-- BEGIN POST -->
        <div class="box">
          <div class="container">
            <div class="title">
              <div class="meta">
                <p class="comments-count"><a href="post_page.html#comments" title="3 comments"><span>3</span> comments</a></p>
                <p class="author"><a href="#null" title="Kuba Sto">Kuba Sto</a></p>
                <p>Category two</p>
                <p>September 19, 2010</p>
              </div>
              <div class="top"></div>
              <h2><a href="post_page.html" title="Curabitur at&nbsp;est ultrice posuere orci massa, nonummy consequat faucibus, dolor a&nbsp;odio et&nbsp;orci luctus quis, velit.">Curabitur at&nbsp;est ultrice posuere orci massa, nonummy consequat faucibus, dolor a&nbsp;odio et&nbsp;orci luctus quis, velit.</a></h2>
            </div>
            <div class="thumbnail">
              <a href="post_page.html" title="Curabitur at&nbsp;est ultrice posuere orci massa, nonummy consequat faucibus, dolor a&nbsp;odio et&nbsp;orci luctus quis, velit.">
                <img src="content/small/p3/a.jpg" alt="" />
                <span class="badge"></span>
              </a>
            </div>
            <div class="excerpt">
              <p>Timeam placerat reprehendunt vim ne, mazim possit takimata eum et. Id&nbsp;diceret ornatus appetere sea, vitae explicari conceptam cum ne. No&nbsp;sed denique mnesarchum, sed ne&nbsp;mollis iudicabit theophrastus, cu&nbsp;mei graeci discere impedit. Per adhuc mandamus et, eius utamur te&nbsp;mel. Vel duis voluptaria ne. Eum id&nbsp;iudicabit efficiendi, quodsi vivendo conceptam eu&nbsp;sed. Ut&nbsp;mel erat suscipiantur consectetuer, ex&nbsp;quo novum. Timeam placerat reprehendunt vim ne, mazim possit takimata eum et. Id&nbsp;diceret ornatus appetere sea.</p>
            </div>
            <div class="bottom"></div>
            <a href="post_page.html" title="Read more" class="more">Read more</a>
          </div>
        </div>
        <!-- END POST -->

        <!-- BEGIN POST -->
        <div class="box">
          <div class="container">
            <div class="title">
              <div class="meta">
                <p class="comments-count"><a href="post_page.html#comments" title="5 comments"><span>5</span> comments</a></p>
                <p class="author"><a href="#null" title="Author's name">Author's name</a></p>
                <p>Category one, Category two</p>
                <p>August 18, 2010</p>
              </div>
              <div class="top"></div>
              <h2><a href="post_page.html" title="Nonummy consequat faucibus, dolor a&nbsp;odio et&nbsp;orci luctus consequat">Nonummy consequat faucibus, dolor a&nbsp;odio et&nbsp;orci luctus consequat</a></h2>
            </div>
            <div class="thumbnail">
              <a href="post_page.html" title="Nonummy consequat faucibus, dolor a&nbsp;odio et&nbsp;orci luctus consequat">
                <img src="content/small/p4/a.jpg" alt="" />
                <span class="badge cool"></span>
              </a>
            </div>
            <div class="excerpt">
              <p>No sed denique mnesarchum, sed ne&nbsp;mollis iudicabit theophrastus, cu&nbsp;mei graeci discere impedit. Per adhuc mandamus et, eius utamur te&nbsp;mel. Velduis voluptaria ne. Eum id&nbsp;iudicabit efficiendi, quodsi vivendo conceptam eu&nbsp;sed. Ut&nbsp;mel erat suscipiantur consectetuer, ex&nbsp;quo novum saperet fierent. Nobis delenit no&nbsp;vius an&nbsp;autem sententiae signiferumque.</p>
            </div>
            <div class="bottom"></div>
            <a href="post_page.html" title="Read more" class="more">Read more</a>
          </div>
        </div>
        <!-- END POST -->

        <!-- BEGIN POST -->
        <div class="box">
          <div class="container">
            <div class="title">
              <div class="meta">
                <p class="comments-count"><a href="post_page.html#comments" title="8 comments"><span>8</span> comments</a></p>
                <p class="author"><a href="#null" title="Kuba Sto">Kuba Sto</a></p>
                <p>Category one, Category two</p>
                <p>August 17, 2010</p>
              </div>
              <div class="top"></div>
              <h2><a href="post_page.html" title="Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue.">Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue.</a></h2>
            </div>
            <div class="thumbnail">
              <a href="post_page.html" title="Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue.">
                <img src="content/small/p5/a.jpg" alt="" />
                <span class="badge"></span>
              </a>
            </div>
            <div class="excerpt">
              <p>Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncusiet. Maecenas tempus, tellus egetarit condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et&nbsp;ante tincidunt tempus. Donec vitae sapien ut&nbsp;libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.</p>
            </div>
            <div class="bottom"></div>
            <a href="post_page.html" title="Read more" class="more">Read more</a>
          </div>
        </div>
        <!-- END POST -->