	<!-- BEGIN IMAGE PRELOADER -->
    <div id="image-preloader">
      <div class="search-background"></div>
      <div class="search-submit"></div>
      <div class="loader"></div>
    </div>
    <!-- END IMAGE PRELOADER -->

    <!-- BEGIN BROWSER NOTIFICATION -->
    <div class="browser-notification ie6">
      <div class="text">
        Your browser (Internet Explorer 6) is <strong>out of date</strong>. It has known <strong>security flaws</strong> and may <strong>not display all features</strong> of this and other websites. <a href="http://www.browser-update.org/update.html">Learn how to update your browser</a>.
      </div>
      <div class="close">X</div>
    </div>
    <noscript>
      <div class="browser-notification js">
        <div class="text">
          Your browser does not support JavaScript, or you do not have it enabled. <strong>Please enable JavaScript</strong> or the site will not work properly.
        </div>
      </div>
    </noscript>
    <!-- END BROWSER NOTIFICATION -->