<!-- BEGIN MASK -->
        <div class="mask"></div>
        <!-- END MASK -->

        <!-- BEGIN SOCIAL MEDIA -->
        <ul id="social-media">
          <li><a href="#null" title="Flickr"><img src="images/socialmedia/white/flickr.png" alt="" /></a></li>
          <li><a href="#null" title="Twitter"><img src="images/socialmedia/white/twitter.png" alt="" /></a></li>
          <li><a href="#null" title="Facebook"><img src="images/socialmedia/white/facebook.png" alt="" /></a></li>
          <li><a href="#null" title="LinkedIn"><img src="images/socialmedia/white/linkedin.png" alt="" /></a></li>
        </ul>
        <!-- END SOCIAL MEDIA -->

        <!-- BEGIN CONTAINER -->
        <div class="container">

          <!-- BEGIN LOGO -->
          <div id="logo" class="arrow">
            <div class="image">
              <img src="schemes/bright-blue/images/logo.png" alt="Stuff" width="137" height="67" />
            </div>
            <a href="index.html" title="Stuff" class="mask"></a>
          </div>
          <!-- END LOGO -->

          <!-- BEGIN NAVIGATION MENU -->
          <div id="nav-menu">
            <div class="arrow up"><div></div></div>
            <div class="container">
              <ul>
                <li><a href="custom_page.html" title="Page">Page</a></li>
                <li><a href="three_column_page.html" title="3 columns">3 columns</a></li>
                <li><a href="portfolio_big.html" title="Portfolio XL">Portfolio XL</a></li>
                <li><a href="portfolio_small.html" title="Portfolio M">Portfolio M</a></li>
                <li><a href="/backend" title="Backend">Backend</a></li>
                <li><a href="/login" title="Login">Login</a></li>
                <li><a href="contact.html" title="Contact">Contact</a></li>
                <li class="search">
                  <a title="Search">Search</a><br />
                  <form action="search.html" method="post">
                    <div>
                      <input type="text" name="s" />
                      <input type="submit" value="" />
                    </div>
                  </form>
                </li>
              </ul>
            </div>
            <div class="arrow down"><div></div></div>
          </div>
          <!-- END NAVIGATION MENU -->

        </div>
        <!-- END CONTAINER -->
