<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>ZF Quickstart Application</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'index'),
            'default',
            true) ?>">Index</a>
            
        <a href="<?php echo $this->url(
            array('controller'=>'guestbook'),
            'default',
            true) ?>">Guestbook</a>
            
        <a href="<?php echo $this->url(
            array('controller'=>'album'),
            'default',
            true) ?>">Album</a>
            
        <a href="<?php echo $this->url(
            array('controller'=>'pet'),
            'default',
            true) ?>">Pet</a>
            
        <a href="<?php echo $this->url(
            array('controller'=>'language'),
            'default',
            true) ?>">Language</a>
            
        <a href="<?php echo $this->url(
            array('controller'=>'user'),
            'default',
            true) ?>">User</a>
        <a href="<?php echo $this->url(
            array('controller'=>'user', 'action' => 'logout'),
            'default',
            true) ?>">Logout</a>
    </div>
</div>

<?php echo $this->layout()->content ?>

</body>
</html>
