<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">

  <!-- BEGIN HEAD -->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <!-- BEGIN CONFIGURATION -->
    <title>Stuff</title>                      <!-- site title -->
    <style type="text/css">
      #menu { width: 250px; }                 /* left menu section width */
      #content { left: 250px; }               /* space between left edge of the browser's window and content (it should be equal or bigger then menu section width) */
    </style>
    <script type="text/javascript">
      stuff_config = {
        middlePoint: 310,                     // distance from page top to post thumbnail's center
        portfolioGalleryChangeEffect: 'fade', // portfolio's gallery transition effect (sliceDown, sliceDownLeft, sliceUp, sliceUpLeft, sliceUpDown, sliceUpDownLeft, fold, fade, random)
        portfolioGalleryChangeSpeed: 150,     // transition speed
        portfolioGalleryNavOnHover: true,     // show navigation arrows only for mouse hover
        columnSupport: true,                  // content coulmns creating
        columnPageChangeSpeed: 'normal',      // change page animation speed (fast, normal, slow)
        mouseWheelSupport: true               // support for horizontal mouse scrolling
      }
    </script>
    <!-- END CONFIGURATION -->

    <link rel="profile" href="http://gmpg.org/xfn/11" />
    <link rel="stylesheet" type="text/css" media="all" href="style.min.css" />
    <link rel="stylesheet" type="text/css" media="all" href="schemes/bright-blue/style.css" />
    <!--[if lt IE 8]>
    <link rel="stylesheet" href="ie7.min.css" type="text/css" media="screen" />
    <![endif]-->
    <link rel="icon" type="image/png" href="schemes/bright-blue/images/favicon.png" />
    <script type="text/javascript" src="schemes/bright-blue/style.js"></script>
    <!-- Java Scripts used in the template - not combined version.
         Delete this code section if you don't need that. -->
    <!--
    <script type="text/javascript" src="js/scripts/jquery-1.4.4.min.js"></script>
    <script type="text/javascript" src="js/scripts/jquery.nivo.slider.pack.js"></script>
    <script type="text/javascript" src="js/scripts/jquery.fancybox-1.3.4.pack.js"></script>
    <script type="text/javascript" src="js/scripts/autocolumn.min.js"></script>
    <script type="text/javascript" src="js/scripts/cufon-yui.js"></script>
    <script type="text/javascript" src="js/scripts/league_gothic.font.js"></script>
    <script type="text/javascript" src="js/scripts/stuff.js"></script>
    -->
    <script type="text/javascript" src="js/stuff.allinone.min.js"></script>
  </head>
  <!-- END HEAD -->

  <!-- BEGIN BODY -->
  <body>

    <!-- BEGIN HEADER -->
    <?= $this->render('partials/header.phtml') ?>
    <!-- END HEADER -->
    

    <!-- BEGIN WRAPPER -->
    <div id="wrapper">

      <!-- BEGIN MENU -->
      <div id="menu">
		<?= $this->render('partials/menu.phtml') ?>
      </div>
      <!-- END MENU -->

      <!-- BEGIN CONTENT -->
      <div id="content">
		<?= $this->render('partials/content.phtml') ?>
        

      </div>
      <!-- END CONTENT -->

      <!-- BEGIN LOADER -->
      <div id="loader"></div>
      <!-- END LOADER -->

    </div>
    <!-- END WRAPPER -->

  </body>
  <!-- END BODY -->

</html>